config/routes.rb
RRApp13::Application.routes.draw do
  

  match '/login'  => 'sessions#new'
  
  match '/auth'  => 'sessions#create'
  
  match '/logout'  => 'sessions#destroy'
  
  match '/contact'  => 'pages#contact'
  
  match '/whoweare' => 'pages#whoweare'
  
  root :to => 'users#index'
 
  get "pages/home"

  get "pages/contact"

  get "pages/whoweare"
  

  resources :users
  
  resources :sessions

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery! #this activate socery
  
attr_accessible  :email, :password, :password_confirmation 

email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

validates :password, :presence => true

validates :password, :presence => true,
                     :confirmation => true,
                     :length => { :within => 6..20 }

validates :email, :presence => true,
                  :format   => { :with => email_regex }
                
def self.findbar(name="")
    self.where('username LIKE ?', name)
end

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  
  def not_authenticated
    redirect_to login_url, :alert => "First loggin to access this page"
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def whoweare
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = login(params[:session][:email], params[:session][:password])
    if user
      redirect_back_or_to root_path, :notice => "Logged in"
    else
      flash.now.alert = "Email or password invalid"
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to root_url, :notice => "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :only => "edit"
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
      format.xml { render xml: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def flash_class(name)
    case name 
    when :alert   then "alert"
    when :notice  then "alert alert-info"
    when :success then "alert alert-success"
    when :error   then "alert alert-error"  
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<!--Footer-->
<div class="clear"></div>

	
	<!-- kipping the footer at the bottom of page -->
	<div id="push"></div>
<footer>
 <p>&copy; Company 2012</p>
</footer>
        
</body>
</html>

app/views/layouts/_header.html.erb
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">

<head>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
      
    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="images/favicon.png" />
    <!-- EOF favicon -->
     
      <!-- Main css -->
    <%= stylesheet_link_tag    "css/style", :media => "all" %>
      
      <!-- Bootstrap css -->
    <%= stylesheet_link_tag    "bootstrap/css/bootstrap", :media => "all" %>
    <%= stylesheet_link_tag    "bootstrap/css/bootstrap-responsive", :media => "all" %>
    
	
        <!-- Bootstrap JS -->
    <%= javascript_include_tag    "bootstrap/js/bootstrap-transition"%>
    <%= javascript_include_tag    "bootstrap/js/bootstrap-alert"%>
    <%= javascript_include_tag    "bootstrap/js/bootstrap-modal"%>
    <%= javascript_include_tag    "bootstrap/js/bootstrap-scrollspy"%>
    <%= javascript_include_tag    "bootstrap/js/bootstrap-tab"%>
    <%= javascript_include_tag    "bootstrap/js/bootstrap-tooltip"%>
    <%= javascript_include_tag    "bootstrap/js/bootstrap-popover"%>
    <%= javascript_include_tag    "bootstrap/js/bootstrap-button"%>
    <%= javascript_include_tag    "bootstrap/js/bootstrap-collapse"%>
    <%= javascript_include_tag    "bootstrap/js/bootstrap-carousel"%>
    <%= javascript_include_tag    "bootstrap/js/bootstrap-typeahead"%>
    	<!-- EOF Bootstrap JS -->
              
</head>
<!-- EOF head -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
  
<%= render 'layouts/header' %>
  
<!-- BeginBody -->
<body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Chambre des m&eacute;tiers de Saint Louis</a>
          
          <!-- Login info + menu -->
          
          <div class="btn-group pull-right">
            <% if current_user %>
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i> <%= current_user.email %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="#">Profile</a></li>
              <li class="divider"></li>
              <li><a href="<%= logout_path %>">Sign Out</a></li>
            </ul>
          <% else  %>
            <%= link_to 'Connexion',login_path, :class => "btn"  %>
           
          <% end %>  
          </div>
          
          <!-- EOF Login info + menu -->
          
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to 'Accueil', root_path %></li>
              <li class="active"><%= link_to 'Qui sommes nous?', whoweare_path %></li>
              <li><%= link_to 'Contact', contact_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>  

<!-- main container -->
<div id="container">
  <% flash.each do  |name, msg|  %>
    <%= content_tag :div , msg, :id => "flash_#{name}", :class => "#{flash_class name}"%>
  <% end %>
    
            <%= yield %>

</div>    
<!-- EOF main container -->

<%= render 'layouts/footer' %>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/whoweare.html.erb
<h1>Pages#whoweare</h1>
<p>Find me in app/views/pages/whoweare.html.erb</p>

app/views/users/_form.html.erb
<%= simple_form_for @user, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :email, :label => "Em@il:", :placeholder => "ndjido@gmail.com", :wrapper_html => { :class => 'control-group' } %>
    <%= f.input :password, :labe => "Password:", :placeholder => "", :wrapper_html => { :class => 'control-group' } %>
    <%= f.input :password_confirmation, :label => "confirmation:", :placeholder => "", :wrapper_html => { :class => 'control-group' } %>
    <%= f.button :submit, :class => 'btn btn-primary' %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table">
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= gravatar_image_tag user.email %></td>
    <td></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user, :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Edit', edit_user_path(user), :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-mini' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path, :class => 'btn' %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <%= gravatar_image_tag @user.email %>
</p>

<p>
  <b>Name:</b>
  <%= @user.email %>
</p>

<p>
  <b>Email:</b>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>